### ISSUE TITLE
Undefined functions

### ISSUE THREAD

**Issue by pcarbo** [simingz/ctwas#26]
These functions are used in various places but as far as I can tell are not defined anywhere in the package:

```
warning_message
read_ld_Rvar_RDS
read_weight_fusion
compute_tf_Xb
compute_tf_Xty
compute_tf_cm
compute_tf_csd
compute_tf_d
```

**Comment by kevinlkx** [comment]
thanks Peter. These should be functions used in the old version of the package. I will check and remove those.

**Comment by pcarbo** [comment]
In these lines, "seqnames", "start" and "end" are also undefined. Not quite sure which packages these are from.
 
```r
gene_annot_gr$chrom <- seqnames(gene_annot_gr)
gene_annot_gr$start_pos <- start(gene_annot_gr)
gene_annot_gr$end_pos <- end(gene_annot_gr)
```

**Comment by kevinlkx** [comment]
those should be from GenomicRanges package. I will import that.

**Comment by kevinlkx** [comment]
these functions should be fixed now.
