### ISSUE TITLE
Remove help pages for non-exported functions

### ISSUE THREAD

**Issue by pcarbo** [simingz/ctwas#27]
I see that many of the help pages are for non-exported functions, which presumably means they should not be called by the user, e.g.,

```r
library(ctwas)
help(read_pvar)
```

I understand if you may want some of these help pages for developer documentation, but in general it is confusing for the user, so it should be used sparingly (and if you want these help pages, they should be carefully flagged as "internal").

These help pages are being generated automatically by roxygen2 wherever you have the `#'` syntax. A simple solution is to replace `#'` with an ordinary comment `#` so that the help pages for these non-exported functions are not generated.

**Comment by kevinlkx** [comment]
Thanks Peter! I have updated the roxygen2 documentations with ordinary comment #
