### ISSUE TITLE
excluding genes with poor performance

### ISSUE THREAD

**Issue by Takahiro0113** [simingz/ctwas#33]
Thank you for creating a nice software!
I'm wondering if it makes sense to exclude genes with poor prediction accuracy from prediction model as it could be noisy information.
Do you have any idea?

**Comment by kevinlkx** [comment]
Thanks for your question. `ctwas` assumes the genes included in the prediction model **already** have good prediction accuracy.  You should only include genes with good prediction accuracy in the model, e.g. FUSION has a heritability cutoff when training the model.
